### ISSUE TITLE
香港UPS抓取轨迹失败

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1594]
[[超长消息]19-09-2018 .pdf](https://github.com/itdida/itdida-issues/files/2399350/19-09-2018.pdf)
上面是长日志
c.i.c.s.httpclient.HttpClientService.getResponseString - 网络错误
java.lang.Exception: 网络请求错误，错误码：302
        at com.itdida.core.services.httpclient.HttpClientService.getResponseString(HttpClientService.java:125)
        at com.itdida.core.services.httpclient.HttpClientService.getResponseString(HttpClientService.java:138)
        at com.itdida.core.services.waybill.ups.HKUPSService.getTrackingResult(HKUPSService.java:741)
        at com.itdida.core.services.waybill.ProcessService.batchTrack(ProcessService.java:185)
        at com.itdida.robots.schedule.waybill.track.UpsTrackRobot$UpsTrackThread.run(UpsTrackRobot.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
19-09-2018 19:04:25.877 [taskExecutor-4530] WARN  c.i.c.s.waybill.ups.HKUPSService.getTrackingResult - 获取UPS派送轨迹结果失败[1Z4F148R0447169287]
java.lang.NullPointerException: null

**Comment by johnnyZchan** [comment]
@WENLINRONG  alpha和hotfix都pr了，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
